import { Producto } from '@/types';

export const productosMock: Producto[] = [
  {
    id: '1',
    nombre: 'Mameluco Osito',
    descripcion: 'Suave mameluco con diseño de osito, ideal para recién nacidos.',
    precio: 349,
    talla: 'RN',
    categoria: 'Unisex',
    imagen: 'https://images.unsplash.com/photo-1522771930-78848d9293e8?w=400&h=400&fit=crop',
    stock: 15,
    disponible: true,
    creadoEn: new Date().toISOString(),
  },
  {
    id: '2',
    nombre: 'Conjunto Marinero',
    descripcion: 'Conjunto de playera y pantalón estilo marinero.',
    precio: 459,
    talla: '3-6M',
    categoria: 'Niño',
    imagen: 'https://images.unsplash.com/photo-1519689680058-324335c77eba?w=400&h=400&fit=crop',
    stock: 10,
    disponible: true,
    creadoEn: new Date().toISOString(),
  },
  {
    id: '3',
    nombre: 'Vestido Florecitas',
    descripcion: 'Hermoso vestido con estampado de flores para tu princesa.',
    precio: 529,
    talla: '6-9M',
    categoria: 'Niña',
    imagen: 'https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?w=400&h=400&fit=crop',
    stock: 8,
    disponible: true,
    creadoEn: new Date().toISOString(),
  },
  {
    id: '4',
    nombre: 'Pijama Estrellitas',
    descripcion: 'Pijama calentita con estampado de estrellas.',
    precio: 389,
    talla: '0-3M',
    categoria: 'Unisex',
    imagen: 'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?w=400&h=400&fit=crop',
    stock: 20,
    disponible: true,
    creadoEn: new Date().toISOString(),
  },
  {
    id: '5',
    nombre: 'Gorrito Conejito',
    descripcion: 'Gorrito tejido con orejitas de conejo.',
    precio: 189,
    talla: 'RN',
    categoria: 'Accesorios',
    imagen: 'https://images.unsplash.com/photo-1555252333-9f8e92e65df9?w=400&h=400&fit=crop',
    stock: 30,
    disponible: true,
    creadoEn: new Date().toISOString(),
  },
  {
    id: '6',
    nombre: 'Body Arcoíris',
    descripcion: 'Body de algodón con estampado de arcoíris.',
    precio: 279,
    talla: '9-12M',
    categoria: 'Unisex',
    imagen: 'https://images.unsplash.com/photo-1519689373023-dd07c7988603?w=400&h=400&fit=crop',
    stock: 12,
    disponible: true,
    creadoEn: new Date().toISOString(),
  },
  {
    id: '7',
    nombre: 'Chamarra Denim',
    descripcion: 'Mini chamarra de mezclilla para bebé con estilo.',
    precio: 599,
    talla: '12-18M',
    categoria: 'Niño',
    imagen: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=400&h=400&fit=crop',
    stock: 5,
    disponible: true,
    creadoEn: new Date().toISOString(),
  },
  {
    id: '8',
    nombre: 'Set de Calcetines',
    descripcion: 'Pack de 5 pares de calcetines con diseños adorables.',
    precio: 159,
    talla: '0-3M',
    categoria: 'Accesorios',
    imagen: 'https://images.unsplash.com/photo-1566454544259-f4b94c3d758c?w=400&h=400&fit=crop',
    stock: 25,
    disponible: true,
    creadoEn: new Date().toISOString(),
  },
  {
    id: '9',
    nombre: 'Vestido Tul Rosa',
    descripcion: 'Vestido de tul rosa con detalles de brillos.',
    precio: 649,
    talla: '18-24M',
    categoria: 'Niña',
    imagen: 'https://images.unsplash.com/photo-1519278409-1f56fdda7485?w=400&h=400&fit=crop',
    stock: 7,
    disponible: true,
    creadoEn: new Date().toISOString(),
  },
  {
    id: '10',
    nombre: 'Pantalón Jogger',
    descripcion: 'Pantalón jogger cómodo de algodón orgánico.',
    precio: 329,
    talla: '12-18M',
    categoria: 'Unisex',
    imagen: 'https://images.unsplash.com/photo-1471286174890-9c112ffca5b4?w=400&h=400&fit=crop',
    stock: 0,
    disponible: false,
    creadoEn: new Date().toISOString(),
  },
];
